baseurl = "https://appfckr.com"
languageCode = "en"
title = "AppFckr"
theme = "Hucore"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/mgjohansen\" target=\"_blank\">Twitter</a> | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"
disqusShortname = "appfckr"
googleAnalytics = ""

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "The Tech Blog of Matt Tate (@mattthehoople)"
keywords = ["software development", "software engineering"]
author = "Matt Tate"
sharingicons = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/mattthehoople"
fa_icon = "fa-github"

#[[params.social]]
#url = "https://gitlab.com/mattthehoople"
#fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/mattthehoople"
fa_icon = "fa-twitter"

#[[params.social]]
#url = "https://linkedin.com/in/mgjohansen"
#fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

#[[params.socialshare]]
#url = "https://linkedin.com/in/mgjohansen"
#fa_icon = "fa-linkedin-square"
